# YAML reference file for NAPALM compliance_report validation
---
- get_facts:
    hostname: R1
    vendor: Cisco

- get_interfaces:
     FastEthernet0/0:
        is_up: true

- get_interfaces_ip:
    Loopback0:
        ipv4:
            10.1.1.1:
                prefix_length: 32
            _mode: strict