## Nornir 3.0 Config File 

inventory:
    plugin: SimpleInventory
    options: 
        host_file: "./inventory/rtrs-cisco-simple/hosts.yaml"
        group_file: "./inventory/rtrs-cisco-simple/groups.yaml"
        defaults_file: "./inventory/rtrs-cisco-simple/defaults.yaml"

runner: 
    plugin: threaded
    options: 
        # max number of devices connections
        num_workers: 20