# Nornir groups file
---
cisco_rtrs:
  port: 22
  username: sntuser
  password: Ilovenetworks99
  platform: cisco_ios
  data:
    priority: 2
    colour: ciscogroup_pink

junos_rtrs:
  port: 22
  username: sntuser
  password: Ilovenetworks99
  platform: juniper_junos